<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>TrashTechHub.Tests</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.1.1" />
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.8" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\trash-tech-hub.web\trash-tech-hub.web.csproj" />
        <ProjectReference Include="..\trash-tech-hub.infrastructure\trash-tech-hub.infrastructure.csproj" />
        <ProjectReference Include="..\trash-tech-hub.application\trash-tech-hub.application.csproj" />
    </ItemGroup>

</Project>