version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./trash-tech-hub.web/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=personal_blog;Username=${DB_USER};Password=${DB_PASSWORD}
      - AdminSettings__Email=${ADMIN_EMAIL:-admin@trashtechhub.com}
      - AdminSettings__Password=${ADMIN_PASSWORD:-admin}
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy
    container_name: trash-tech-hub-web
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - blog-net
  db:
    image: "postgres:16-alpine"
    container_name: trash-tech-hub-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=personal_blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - blog-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d personal_blog -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
    postgres_data:
networks:
    blog-net:
      driver: bridge
